### ISSUE TITLE
Couldn't import file

### ISSUE THREAD

**Issue by solkar** [keijiro/Klak#1]
I have problems with the teapot model.

>  ImportFBX Errors:
>   Couldn't import file         > /Users/solkar/Developer/Samples/Unity/_keijiro.github.io/Klak/Assets/Test/Teapot.fbx.
> File is corrupted (or invalid)

**Comment by keijiro** [comment]
I can't reproduce this. Which version of Unity are you using?

**Comment by solkar** [comment]
v5.1.4

On Mon, Jan 11, 2016 at 4:53 PM, Keijiro Takahashi <notifications@github.com

**Comment by keijiro** [comment]
Okay. I'll check it later.
P.S. I'm using 5.2.4

**Comment by keijiro** [comment]
Bingo. That's because Unity 5.1 doesn't support FBX2016. I re-exported the model with FBX2014.
1c66c467e6eeabfeeec08c51f0a79b42b893491e

**Comment by solkar** [comment]
Awesome! 
Just curious, how do you know which formats are supported? Is there any reference doc for that?

**Comment by keijiro** [comment]
I saw a note in the changelog that said FBX2016 issue was solved. I'm not sure if there is a doc about it.

**Comment by solkar** [comment]
Neither do I 😁

One chili to bind them into hotness
