### ISSUE TITLE
Particle System Out

### ISSUE THREAD

**Issue by Latentnaut** [keijiro/Klak#22]
Hi Keijiro,

is this a proper way to wire Particle System with Klak? I'm getting a bad performance.

<img width="960" alt="screen shot 2017-01-28 at 15 46 58" src="https://cloud.githubusercontent.com/assets/22867200/22397424/4fa3885e-e571-11e6-8eb5-e729bb985471.png">

Thank you very much!

**Comment by keijiro** [comment]
It seems like okay. It depends on what you're trying to make though.

**Comment by Latentnaut** [comment]
I'm controlling the Emission Rate correctly with the first node 'Particle System Out'.

However, with the second node, 'Threshold', I guess I want to check / uncheck the Emission component of the Particle System, what I'm not achieving.

Where can be the issue? I get only around 30 fps like this :-/

<img width="262" alt="screen shot 2017-01-28 at 17 34 36" src="https://cloud.githubusercontent.com/assets/22867200/22398092/7a691d6a-e580-11e6-9dd0-5b67723e6d88.png">

**Comment by keijiro** [comment]
You can't check/uncheck the emission component with the ParticleSystemOut node.

I'm not sure if it's relevant to the framerate issue.

**Comment by Latentnaut** [comment]
> You can't check/uncheck the emission component with the ParticleSystemOut node.
> 
Then... I cannot figure out what does the ‘Emit’ parameter in this ‘Particle System Out’.

**Comment by keijiro** [comment]
"Emit" can be used to emit a number of particles immediately. It's almost identical to ParticleSystem.Emit.

https://docs.unity3d.com/ScriptReference/ParticleSystem.Emit.html

**Comment by keijiro** [comment]
I'm closing this issue now. Feel free to reopen if you find further issues.

**Comment by Latentnaut** [comment]
Very useful to know, thank you!
