### ISSUE TITLE
Garbage Collection

### ISSUE THREAD

**Issue by kamend** [keijiro/Klak#26]
First, thanks for this awesome tool!

I noticed that in BrownianMotion.cs, you create two new Vector3 on every frame. You will save a lot of memory, if you define private Vector3 variables and just use them every time. This is a real saver on mobile, on Desktop probably it won't be such a problem.

**Comment by keijiro** [comment]
No. Vector3 is struct, so "new Vector3()" never allocate GC memory. To make sure of it, I profiled a minimal project that only has one BrownianMotion. I confirmed that the GC allocation size doesn't move from the initial state.

I'm closing this ticket. Please feel free to reopen if you have any further idea on this topic.
