### ISSUE TITLE
Geometry instances with drop off 

### ISSUE THREAD

**Issue by CJHFUTURE** [keijiro/Klak#28]
Hi I’m loving using this system exsoecially with lasp.
I’m just wondering how hard it would be to create a node that applies a value to a list of geometry with time delay or something similiar. Eg. A row of cubes and the first cube is a master and the others are slaves and copy the motion or inputs on the first but with time offset etc.

**Comment by CJHFUTURE** [comment]
If possible this would be a super cool way to control large amounts of geometrybwith minimal patching

**Comment by keijiro** [comment]
Even though you can use the Delay node to delay events, it's not recommended to use the Wiring system with "large amounts of geometry". I can admit that Klak is super inefficient in performance/memory wise. You should use another performant system for such cases.

I'm closing this issue. Please feel free to reopen if you have further questions.

**Comment by CJHFUTURE** [comment]
That’s okay thanks for your assistance :)

_____________________________
