### ISSUE TITLE
Patch start crash in .net 4.5-Unity2018

### ISSUE THREAD

**Issue by phields** [keijiro/Klak#35]
![1](https://user-images.githubusercontent.com/31947421/44710043-c5555b80-aadd-11e8-9dc6-07568e71495b.png)

**Comment by phields** [comment]
Fix:
in node.cs
change 136:
`                var slot = AddInputSlot("set_" + prop.Name, prop.PropertyType);`
to
`                var slot = AddInputSlot("set_" + prop.Name);`

**Comment by phields** [comment]
Sorry, this problem only happens when I use midi Klak project in new Klak.
It's not a bug about Klak.

**Comment by andybak** [comment]
Can confirm this is a general problem (take a clean checkout of the example project on Unity 2018.2.x and switch to C# 4.6)

Also - the fix above seems to work.

**Comment by keijiro** [comment]
I pushed another fix for this issue. https://github.com/keijiro/Klak/commit/9120afc7a7ac8b517d756c13080e9ce1747baa9f

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further questions.
