### ISSUE TITLE
Drag Event Input with Touch Controls/Mouse control? #15

### ISSUE THREAD

**Issue by cemillerena** [keijiro/Klak#39]
Hooked up my scene to have faders that track my knobs in the OP-Z.

I have set up the Drag Event Input to a Knob Out and I thought this was also carried to iOS touch control but I was wrong. When I use the Mouse Button Input I don't get the same results. What's the correct way to set up a drag event input with touch controls? 

Thanks!

**Comment by keijiro** [comment]
Neither "Drag Event Input" nor "Knob Out" is implemented in my version of Klak, so I can't provide a correct answer for the question. Please wait for a reply from the OP-Z team.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.
