### ISSUE TITLE
Binding Klak objects to UIelements

### ISSUE THREAD

**Issue by mr-brooks-dev** [keijiro/Klak#42]
Hello,
I was curious if it would even be possible to bind sliders and toggles in UIelements to Klak objects?
https://docs.unity3d.com/Manual/UIE-Binding.html

Apparently as long as it is serialized, it can be bound to things within UIelements. 

Should I give up on this idea?

**Comment by keijiro** [comment]
I think it's possible, but it would be better to implement a mediator classes like KlakUI: https://github.com/keijiro/KlakUI

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further questions.
