### ISSUE TITLE
Patcher window

### ISSUE THREAD

**Issue by bryanrtboy** [keijiro/Klak#7]
If a Patcher window does not already exist in the Editor Layout, an error is thrown in the Console when using the "Open Patcher" button in the Scene:
`System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)`

The issue goes away if a tab in the Editor is the Patch object. This is in 5.4b22 and it does not crash the scene, just an annoying error message.

**Comment by keijiro** [comment]
Thanks for reporting. I'll look into it.

**Comment by bryanrtboy** [comment]
Great! Hey, I really like your work - both art and code. Very cool!

**Comment by keijiro** [comment]
It doesn't reproduce with Unity 5.4.1.
